#!/usr/bin/env python3
"""Regenerate lib/font_metrics.dart from the DIN Pro OTFs.

Flutter has no runtime API for glyph side bearings, so we bake them into a
table. Run this if assets/fonts ever changes:

    pip install fonttools
    python3 tool/gen_font_metrics.py
"""

from fontTools.ttLib import TTFont
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONTS = [
    ("regular", "assets/fonts/FF_DIN_Pro_Regular_Italic.otf"),
    ("bold", "assets/fonts/FF_DIN_Pro_Bold_Italic.otf"),
]


def bearings(path):
    f = TTFont(ROOT / path)
    upm = f["head"].unitsPerEm
    hmtx, cmap = f["hmtx"], f.getBestCmap()
    out = {}
    for cp, gname in cmap.items():
        if 0x20 <= cp < 0x7F:
            out[chr(cp)] = round(hmtx[gname][1] / upm, 4)
    return out


def dart_map(vals):
    lines = []
    for ch, v in sorted(vals.items()):
        esc = {"'": "\\'", "\\": "\\\\", "$": "\\$"}.get(ch, ch)
        lit = f"'{esc}'"
        lines.append(f"    {lit}: {v},")
    return "\n".join(lines)


parts = []
for name, path in FONTS:
    parts.append(
        f"  /// Left side bearing per character, as a fraction of the em, read\n"
        f"  /// from {pathlib.Path(path).name}.\n"
        f"  static const Map<String, double> _{name} = {{\n"
        f"{dart_map(bearings(path))}\n"
        f"  }};\n"
    )

src = f'''// font_metrics.dart — GENERATED by tool/gen_font_metrics.py. Do not edit.
//
// Per-glyph left side bearings for DIN Pro. See [FontMetrics.leftBearing].

import 'package:flutter/material.dart';

/// Glyph metrics that Flutter does not expose at runtime.
class FontMetrics {{
  const FontMetrics._();

  /// The only family these tables describe. Any other family gets no
  /// correction — a wrong correction is worse than none.
  static const String family = 'DINPro';

{chr(10).join(parts)}
  /// Horizontal distance, in logical pixels, from the left edge of [text]'s
  /// layout box to the left edge of its first glyph's INK.
  ///
  /// Returns 0 for families we have no table for, and for empty text.
  static double leftBearing(String text, TextStyle style) {{
    if (text.isEmpty || style.fontFamily != family) return 0;
    final table = (style.fontWeight?.value ?? 400) >= 700 ? _bold : _regular;
    final em = table[text[0]];
    if (em == null) return 0;
    return em * (style.fontSize ?? 14.0);
  }}
}}
'''

(ROOT / "lib/font_metrics.dart").write_text(src)
print("wrote lib/font_metrics.dart")
